version: 5.0.{build}

branches:
  only:
  - master

image: Visual Studio 2017

platform: Any CPU

environment:
  matrix:
    # node.js
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami

before_build:
  - node --version
  - npm --version

build_script:
  - npm run build

test_script:
  - npm test

deploy_script:
  - ps: |
      if ($env:nodejs_version -eq "8")
      {
        iex "npm publish dist --access=public"
      }
cache:
  - node_modules -> package-lock.json
  - '%APPDATA%\npm-cache'
