version: 5.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_non_tags: true

image: Visual Studio 2017

platform: Any CPU

environment:
  npm_auth_token:
    secure: 2G57TJwGR3m40UD1G7YdkowFzezrhOxEzMKwehKpb1vNPbsbFzfKRIFYVQ7WzZzE
  matrix:
    # node.js
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  - node --version
  - npm --version

build_script:
  - npm run build

test_script:
  - npm test

deploy_script:
  - ps: |
      if ($env:nodejs_version -eq "6")
      {
        iex "npm pack ./dist --access=public"
        iex "npm publish ./dist --access=public"
      }
cache:
  - node_modules -> package-lock.json
  - '%APPDATA%\npm-cache'
