version: 6.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
platform: Any CPU
environment:
  ANGULAR_BUILD_TELEMETRY_OPTOUT: 1
  nodejs_version: "8"
matrix:
  fast_finish: true
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
build_script:
  - npm run build:samples
test: off
cache:
  - node_modules -> package-lock.json
  - '%APPDATA%\npm-cache'
