version: 4.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017 Preview
platform: Any CPU
environment:
  matrix:
    # node.js
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  #- ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  #- yarn --frozen-lockfile
  - npm install -g npm@latest
  - npm install

build_script:
  - ps: npm run build

# Post-install test scripts.
test_script:
  - node --version
  #- yarn --version
  - npm --version

cache:
  - node_modules
  #- "%LOCALAPPDATA%/Yarn"
matrix:
  fast_finish: true