pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_non_tags: true
clone_depth: 1
image: Visual Studio 2017
platform: Any CPU
environment:
  ANGULAR_BUILD_TELEMETRY_OPTOUT: 1
  nodejs_version: "8"
matrix:
  fast_finish: true
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - ps: |
      if ($env:npm_auth_token)
      {
        iex '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
        iex "npm whoami"
      }
  - npm install
build_script:
  - npm run build
  - npm run test
test: off
deploy_script:
  - ps: |
      if ($env:npm_auth_token)
      {
        iex "npm publish ./dist --access=public"
      }
cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'
