version: '{build}'
image: 'Visual Studio 2019'
clone_depth: 1
environment:
  nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --frozen-lockfile
build_script:
  - yarn build
  - yarn build:samples
test: "off"
cache:
  - node_modules -> yarn.lock
  - "%LOCALAPPDATA%\\Yarn"
