version: 5.0.{build}

branches:
  only:
  - master

image: Visual Studio 2017

platform: Any CPU

environment:
  matrix:
    # node.js
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

matrix:
  fast_finish: true

install:
  #- ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm install

build_script:
  - ps: npm run build

# Post-install test scripts.
test_script:
  - npm run test

cache:
  - node_modules -> package-lock.json
