sudo: false
dist: trusty
language: node_js
git:
  depth: 1
matrix:
  include:
    - os: linux
      node_js: "node"
    # - os: linux
    #   node_js: "10"
    - os: osx
      node_js: "node"
    # - os: osx
    #   node_js: "10"
  fast_finish: true
install:
  - yarn install --frozen-lockfile
script:
  - yarn build
  - yarn build:samples
cache: yarn
