dist: trusty
sudo: false

language: node_js

node_js:
  - "6"
  - "lts/*"
  - "node"

env:
  - NODE_ENV=TEST

cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g npm@latest

install:
  - npm install

script:
  - npm run build
  - npm run test:build-all
