sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      node_js: "node"
    - os: linux
      node_js: "stable"
    - os: osx
      node_js: "stable"
  fast_finish: true

install:
  - npm install

script:
  - npm run build
  - npm run test

cache:
  directories:
    - ./node_modules

git:
  depth: 1
