dist: trusty
sudo: false

language: node_js

node_js:
  - "node"

cache:
  directories:
    - ./node_modules

stages:
  - build

matrix:
  fast_finish: true
  allow_failures:
    - env: nightly
    #- node_js: "9"
  include:
    # Build stage
    - stage: build
    - script: npm run build
      env: build
      script: npm test
      env: test

before_install:
  # Install npm.
  - npm install -g npm@latest

install:
  - npm install
