dist: trusty
sudo: false

language: node_js

node_js:
  - "node"

cache:
  directories:
    - ./node_modules

matrix:
  fast_finish: true
  allow_failures:
    - env: nightly
    #- node_js: "9"

before_install:
  # Install npm.
  - npm install -g npm@latest

install:
  - npm install

  script:
    - npm run build
