sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master

env:
  global:
    - ANGULAR_BUILD_TELEMETRY_OPTOUT: 1

matrix:
  include:
    - os: linux
      node_js: "node"
      env: JOB_PART=build
    - os: linux
      node_js: "stable"
      env: JOB_PART=test
    - os: osx
      node_js: "stable"
      env: JOB_PART=test
  fast_finish: true
  allow_failures:
    - os: osx

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run $JOB_PART
