sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master

env:
  global:
    - ANGULAR_BUILD_TELEMETRY_OPTOUT: 1

matrix:
  include:
    - os: linux
      node_js: "node"
      env: JOB_PART=build:test-all
    - os: linux
      node_js: "stable"
      env: JOB_PART=build:test-all
    - os: linux
      node_js: "6"
      env: JOB_PART=build:test-all
    - os: osx
      node_js: "8"
      env: JOB_PART=build:test-all
  fast_finish: true
  allow_failures:
    - os: osx

cache:
  directories:
    - ./node_modules

before_install:
  - if [[ $TRAVIS_NODE_VERSION -lt 8 ]]; then npm install --global npm@~5.6.0; fi
  #- npm install -g npm@~5.6.0

install:
  - npm install

script:
  - npm run $JOB_PART
