dist: trusty
sudo: false

language: node_js

cache:
  #yarn: true
  directories:
     - ./node_modules

matrix:
  fast_finish: false
  allow_failures:
    - env: nightly
    #- node_js: "7"
    #- node_js: "8"
  include:
    - stage: build
    - script: npm run build
      env: build

before_install:
  # Install npm.
  - npm install -g npm@latest
  # Install yarn.
  #- curl -o- -L https://yarnpkg.com/install.sh | bash
  #- export PATH="$HOME/.yarn/bin:$PATH"
  #- yarn config set spin false
  #- yarn config set progress false

install:
  - npm install
  #- yarn --frozen-lockfile