jobs:
  - job: basic
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UseNode@1
        inputs:
          version: '10.9.0'
        displayName: 'Use Node 10.9.0'
      - script: |
          yarn install --frozen-lockfile
        displayName: 'Install dependencies'
      - script: |
          yarn build
        displayName: "Run build"
      - script: |
          yarn build:samples
        displayName: 'Run build samples'
      - script: |
          yarn build:samples
        displayName: 'Run build samples'
      - script: |
          yarn lint
        displayName: 'Run linting'

  - job: Linux
    dependsOn:
      - basic
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      maxParallel: 3
      matrix:
        node-12:
          node_version: '12.x'
        node-10:
          node_version: '10.x'
    steps:
      - task: UseNode@1
        inputs:
          version: $(node_version)
        displayName: 'Use Node $(node_version)'
      - script: |
          yarn install --frozen-lockfile
        displayName: 'Install dependencies'
      - script: |
          yarn build
        displayName: 'Run build'
      - script: |
          yarn build:samples
        displayName: 'Run build samples'

  - job: macOS
    dependsOn:
      - basic
    pool:
      vmImage: 'macOS-latest'
    strategy:
      maxParallel: 3
      matrix:
        node-12:
          node_version: '12.x'
        node-10:
          node_version: '10.x'
    steps:
      - task: UseNode@1
        inputs:
          version: $(node_version)
        displayName: 'Use Node $(node_version)'
      - script: |
          yarn install --frozen-lockfile
        displayName: 'Install dependencies'
      - script: |
          yarn build
        displayName: 'Run build'
      - script: |
          yarn build:samples
        displayName: 'Run build samples'

  - job: Windows
    dependsOn:
      - basic
    pool:
      vmImage: 'windows-latest'
    strategy:
      maxParallel: 3
      matrix:
        node-12:
          node_version: '12.x'
        node-10:
          node_version: '10.x'
    steps:
      - task: UseNode@1
        inputs:
          version: $(node_version)
        displayName: 'Use Node $(node_version)'
      - script: |
          yarn install --frozen-lockfile
        displayName: 'Install dependencies'
      - script: |
          yarn build
        displayName: 'Run build'
      - script: |
          yarn build:samples
        displayName: 'Run build samples'
