version: 2.1

var_1: &docker_image circleci/node:10.12-browsers
var_2: &cache_key v2.1-angular-build-{{ .Branch }}-{{ checksum "yarn.lock" }}-node-10.12

jobs:
  build:
    filters:
        branches:
          only: master
        tags:
          only: /v(?:0|[1-9]\d*)(\.(?:0|[1-9]\d*))?(\.(?:0|[1-9]\d*))?(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?/
    working_directory: ~/angular-build
    docker:
      - image: *docker_image
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          key: *cache_key
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Run build
          command: yarn build
      - run:
          name: Run build samples
          command: yarn build:samples
